"use client";

import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Application, ApplicationStatus } from "@/types/applications";

const STATUS_CONFIG: { id: ApplicationStatus; title: string; color: string }[] = [
  { id: "saved", title: "Saved", color: "bg-slate-400" },
  { id: "applied", title: "Applied", color: "bg-[#26A69A]" },
  { id: "screening", title: "Screening", color: "bg-amber-400" },
  { id: "interviewing", title: "Interviewing", color: "bg-indigo-400" },
  { id: "offer", title: "Offer", color: "bg-emerald-500" },
  { id: "rejected", title: "Rejected", color: "bg-rose-400" },
];

export default function ApplicationsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [applications, setApplications] = useState<Application[]>([]);
  const [loading, setLoading] = useState(true);
  const [view, setView] = useState<'kanban' | 'list'>('kanban');
  const [showNewModal, setShowNewModal] = useState(false);

  // Trust/AI Disclosure Banner
  // This should be visible before any export/save/use of generated content
  // per Build Spec 4.2

  const DisclosureBanner = () => (
    <div className="mb-6 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 shadow-sm">
      <strong>Disclosure:</strong> Some application content may be generated by AI using only your approved Career Memory facts.<br />
      <span className="font-semibold">You are responsible for reviewing and editing all AI-generated content before export, save, or use.</span> AI CV Scan does not fabricate experience, credentials, or achievements, but cannot guarantee the accuracy or appropriateness of AI output.<br />
      <span className="italic">Do not submit generated content to employers without careful review.</span>
    </div>
  );

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/auth/signin");
    } else if (status === "authenticated") {
      fetchApplications();
    }
  }, [status, router]);

  const fetchApplications = async () => {
    try {
      const res = await fetch("/api/applications");
      const data = await res.json();
      setApplications(data.applications || []);
    } catch (err) {
      console.error("Failed to fetch applications:", err);
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (appId: string, newStatus: ApplicationStatus) => {
    try {
      await fetch(`/api/applications/${appId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus }),
      });
      setApplications(apps => 
        apps.map(app => app.id === appId ? { ...app, status: newStatus } : app)
      );
    } catch (err) {
      console.error('Failed to update status:', err);
    }
  };

  const getColumnApps = (status: ApplicationStatus) => 
    applications.filter(app => app.status === status);

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'bg-red-500';
      case 'medium': return 'bg-yellow-500';
      case 'low': return 'bg-gray-500';
      default: return 'bg-gray-500';
    }
  };

  if (status === "loading" || loading) {
    return (
      <div className="min-h-screen bg-[#E0F2F1] flex items-center justify-center">
        <div className="text-xl text-[#1A237E]">Loading...</div>
      </div>
    );
  }

  if (!session) return null;

  return (
    <div className="min-h-screen bg-[#E0F2F1]">
      <nav className="container mx-auto flex items-center justify-between px-4 py-6">
        <Link href="/dashboard" className="text-2xl font-bold text-[#1A237E]">
          <span className="text-[#26A69A]">CV</span>Scan
        </Link>
        <div className="flex items-center gap-4">
          <Link href="/dashboard" className="text-[#4E5B7A] hover:text-[#1A237E]">
            Dashboard
          </Link>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-8">
        <DisclosureBanner />

        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8">
          <div>
            <h1 className="mb-2 text-4xl font-bold text-[#1A237E]">Application Tracker</h1>
            <p className="text-[#4E5B7A]">
              {applications.length} applications tracked
            </p>
            <p className="mt-2 text-sm text-[#4E5B7A]">
              Job Packs you generate now create a draft tracker entry automatically.
            </p>
          </div>
          <div className="flex flex-col items-stretch gap-3 sm:flex-row sm:items-center">
            <button
              type="button"
              disabled
              className="cursor-not-allowed rounded-lg border border-black/[0.08] bg-white/70 px-4 py-2 text-sm font-medium text-[#4E5B7A] shadow-sm opacity-70"
            >
              Auto-sync from job boards — Coming Soon
            </button>
            <div className="flex rounded-lg border border-black/[0.08] bg-white p-1 shadow-sm">
              <button
                onClick={() => setView('kanban')}
                className={`px-4 py-2 rounded-md transition-colors ${
                  view === 'kanban' ? 'bg-[#26A69A] text-white' : 'text-[#4E5B7A] hover:text-[#1A237E]'
                }`}
                data-testid="view-kanban"
              >
                Kanban
              </button>
              <button
                onClick={() => setView('list')}
                className={`px-4 py-2 rounded-md transition-colors ${
                  view === 'list' ? 'bg-[#26A69A] text-white' : 'text-[#4E5B7A] hover:text-[#1A237E]'
                }`}
                data-testid="view-list"
              >
                List
              </button>
            </div>
            <button
              onClick={() => setShowNewModal(true)}
              className="rounded-lg bg-[#26A69A] px-6 py-2 font-semibold text-white shadow-sm transition-colors hover:bg-[#1f8f85]"
              data-testid="new-application-btn"
            >
              + Add Application
            </button>
          </div>
        </div>

        {/* Kanban View */}
        {view === 'kanban' && (
          <div className="flex gap-4 overflow-x-auto pb-4" data-testid="kanban-board">
            {STATUS_CONFIG.filter(s => s.id !== 'rejected').map((column) => (
              <div
                key={column.id}
                className="w-72 flex-shrink-0 rounded-2xl border border-black/[0.08] bg-white p-4 shadow-[0_18px_40px_rgba(26,35,126,0.06)]"
              >
                <div className="flex items-center gap-2 mb-4">
                  <div className={`w-3 h-3 rounded-full ${column.color}`} />
                  <h3 className="font-semibold text-[#1A237E]">{column.title}</h3>
                  <span className="text-sm text-[#4E5B7A]">({getColumnApps(column.id).length})</span>
                </div>
                <div className="space-y-3">
                  {getColumnApps(column.id).map((app) => (
                    <Link
                      key={app.id}
                      href={`/dashboard/applications/${app.id}`}
                      className="block cursor-pointer rounded-xl border border-black/[0.06] bg-[#F9FBFB] p-4 transition-all hover:border-[#26A69A]/60 hover:bg-[#F2FBFA] hover:shadow-md"
                      data-testid={`app-card-${app.id}`}
                    >
                      <div className="flex items-start justify-between mb-2">
                        <h4 className="flex-1 truncate font-medium text-[#1A237E]">{app.company}</h4>
                        <div className={`w-2 h-2 rounded-full ${getPriorityColor(app.priority)}`} />
                      </div>
                      <p className="mb-2 truncate text-sm text-[#4E5B7A]">{app.title}</p>
                      <div className="flex items-center justify-between text-xs text-[#607086]">
                        <span>{formatDate(app.created_at)}</span>
                        {app.ats_score && (
                          <span className="text-[#26A69A]">{app.ats_score}%</span>
                        )}
                      </div>
                    </Link>
                  ))}
                  {getColumnApps(column.id).length === 0 && (
                    <div className="py-8 text-center text-sm text-[#607086]">
                      No applications
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* List View */}
        {view === 'list' && (
          <div className="overflow-hidden rounded-2xl border border-black/[0.08] bg-white shadow-[0_18px_40px_rgba(26,35,126,0.06)]" data-testid="list-view">
            <table className="w-full">
              <thead>
                <tr className="border-b border-black/[0.08] bg-[#F7FAFA]">
                  <th className="p-4 text-left font-medium text-[#4E5B7A]">Company</th>
                  <th className="p-4 text-left font-medium text-[#4E5B7A]">Position</th>
                  <th className="p-4 text-left font-medium text-[#4E5B7A]">Status</th>
                  <th className="p-4 text-left font-medium text-[#4E5B7A]">Priority</th>
                  <th className="p-4 text-left font-medium text-[#4E5B7A]">ATS</th>
                  <th className="p-4 text-left font-medium text-[#4E5B7A]">Date</th>
                </tr>
              </thead>
              <tbody>
                {applications.map((app) => (
                  <tr
                    key={app.id}
                    className="cursor-pointer border-b border-black/[0.06] hover:bg-[#F7FAFA]"
                    onClick={() => router.push(`/dashboard/applications/${app.id}`)}
                    data-testid={`list-row-${app.id}`}
                  >
                    <td className="p-4 font-medium text-[#1A237E]">{app.company}</td>
                    <td className="p-4 text-[#4E5B7A]">{app.title}</td>
                    <td className="p-4">
                      <select
                        value={app.status}
                        onChange={(e) => {
                          e.stopPropagation();
                          updateStatus(app.id, e.target.value as ApplicationStatus);
                        }}
                        onClick={(e) => e.stopPropagation()}
                        className="rounded border border-black/[0.08] bg-white px-2 py-1 text-sm text-[#1A237E]"
                      >
                        {STATUS_CONFIG.map(s => (
                          <option key={s.id} value={s.id}>{s.title}</option>
                        ))}
                      </select>
                    </td>
                    <td className="p-4">
                      <span className={`inline-block w-2 h-2 rounded-full ${getPriorityColor(app.priority)} mr-2`} />
                      <span className="capitalize text-[#4E5B7A]">{app.priority}</span>
                    </td>
                    <td className="p-4 text-[#26A69A]">{app.ats_score ? `${app.ats_score}%` : '-'}</td>
                    <td className="p-4 text-[#607086]">{formatDate(app.created_at)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {applications.length === 0 && (
              <div className="py-12 text-center text-[#4E5B7A]">
                No applications yet. Add your first application to get started.
              </div>
            )}
          </div>
        )}
      </div>

      {/* New Application Modal */}
      {showNewModal && (
        <NewApplicationModal
          onClose={() => setShowNewModal(false)}
          onCreated={() => {
            setShowNewModal(false);
            fetchApplications();
          }}
        />
      )}
    </div>
  );
}

function NewApplicationModal({
  onClose,
  onCreated,
}: {
  onClose: () => void;
  onCreated: () => void;
}) {
  const [company, setCompany] = useState("");
  const [title, setTitle] = useState("");
  const [url, setUrl] = useState("");
  const [location, setLocation] = useState("");
  const [source, setSource] = useState("");
  const [priority, setPriority] = useState<"low" | "medium" | "high">("medium");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!company.trim() || !title.trim()) {
      setError("Company and title are required");
      return;
    }

    setLoading(true);
    setError("");

    try {
      const res = await fetch("/api/applications", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          company,
          title,
          url: url || undefined,
          location: location || undefined,
          source: source || undefined,
          priority,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to create application");
      }

      onCreated();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to create application");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1A237E]/20 p-4 backdrop-blur-sm">
      <div className="w-full max-w-lg rounded-2xl border border-black/[0.08] bg-white p-6 shadow-[0_30px_80px_rgba(26,35,126,0.16)]">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold text-[#1A237E]">Add Application</h2>
          <button onClick={onClose} className="text-2xl text-[#607086] hover:text-[#1A237E]">
            ×
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="mb-1 block text-[#1A237E]">Company *</label>
            <input
              type="text"
              value={company}
              onChange={(e) => setCompany(e.target.value)}
              className="w-full rounded-lg border border-black/[0.08] bg-[#F9FBFB] px-4 py-2 text-[#1A237E]"
              placeholder="e.g., Google"
              data-testid="new-app-company"
            />
          </div>

          <div>
            <label className="mb-1 block text-[#1A237E]">Position *</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full rounded-lg border border-black/[0.08] bg-[#F9FBFB] px-4 py-2 text-[#1A237E]"
              placeholder="e.g., Senior Product Manager"
              data-testid="new-app-title"
            />
          </div>

          <div>
            <label className="mb-1 block text-[#1A237E]">Job URL</label>
            <input
              type="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="w-full rounded-lg border border-black/[0.08] bg-[#F9FBFB] px-4 py-2 text-[#1A237E]"
              placeholder="https://..."
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="mb-1 block text-[#1A237E]">Location</label>
              <input
                type="text"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                className="w-full rounded-lg border border-black/[0.08] bg-[#F9FBFB] px-4 py-2 text-[#1A237E]"
                placeholder="Remote, NYC, etc."
              />
            </div>
            <div>
              <label className="mb-1 block text-[#1A237E]">Source</label>
              <select
                value={source}
                onChange={(e) => setSource(e.target.value)}
                className="w-full rounded-lg border border-black/[0.08] bg-[#F9FBFB] px-4 py-2 text-[#1A237E]"
              >
                <option value="">Select...</option>
                <option value="linkedin">LinkedIn</option>
                <option value="indeed">Indeed</option>
                <option value="company_site">Company Site</option>
                <option value="referral">Referral</option>
                <option value="other">Other</option>
              </select>
            </div>
          </div>

          <div>
            <label className="mb-1 block text-[#1A237E]">Priority</label>
            <div className="flex gap-4">
              {(['low', 'medium', 'high'] as const).map((p) => (
                <label key={p} className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="radio"
                    name="priority"
                    value={p}
                    checked={priority === p}
                    onChange={() => setPriority(p)}
                    className="accent-[#26A69A]"
                  />
                  <span className="capitalize text-[#4E5B7A]">{p}</span>
                </label>
              ))}
            </div>
          </div>

          {error && (
            <div className="rounded-lg border border-rose-200 bg-rose-50 p-3">
              <p className="text-sm text-rose-700">{error}</p>
            </div>
          )}

          <div className="flex gap-4 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 rounded-lg border border-black/[0.08] bg-[#F7FAFA] py-2 text-[#1A237E] transition hover:bg-[#EEF7F6]"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 rounded-lg bg-[#26A69A] py-2 font-semibold text-white transition hover:bg-[#1f8f85] disabled:bg-[#7cc8bf]"
              data-testid="new-app-submit"
            >
              {loading ? "Creating..." : "Add Application"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
